<?php
    function generateName():string{
        $nb = rand(1000, 9999);
        $alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        $i1=rand(0, 25);
        $i2=rand(0, 25);
        return $alphabet[$i1].$alphabet[$i2]."-".$nb;
    }
    $name = generateName();
    function inverseName($nameToInverse):string{
        return strrev($nameToInverse);
    }
    function jour(){
        echo date("d m Y");   
    }
    function heure(){
        date_default_timezone_set('Europe/Paris');
        echo date("H:i");
    }
    function defineNumber(int $nb){
        if($nb%2===1){
            echo "J'ai choisi un nombre impair";
        }
        else{
            echo "J'ai choisi un nombre pair";
        }
    }
    function coffeeOrDestruction(){
        $luckNumber=rand(1, 3);
        if ($luckNumber === 1){
            echo "Extermination ! Extermination !";
        }
        else{
            echo "Vous voulez un café ?";
        }
    }
    $MysteriousNumner=rand(1, 1000);
    function findNumber(int $numbers){
        for ($i=0; $i<=1000; $i++){
            if ($numbers===$i){
                echo "le nombre mystère est {$i}";
            }
        }
    }
    function findNumberDicotomie(int $numbers){
        $min=0;
        $max=1000;
        while ($max===$numbers){
            if ($numbers < $max/2){
                $max=$max/2;
            }
            else{
                $min=$max/2;
            }
        }
        echo "le nombre mystère est {$max}";
    }
?>



<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Titre de la page</title>
    <link rel="stylesheet" href="style.css">
</head>

<main>
        <h1>Bonjour Vincent. Je m'appelle <?php echo $name; ?></h1>
        <h2>Nous sommes le <?php jour(); ?>, il est <?php heure(); ?></h2>
        <h2>J'ai choisi le nombre <?php echo $nb = rand(0, 9999); ?>. <?php defineNumber($nb); ?></h2>
        <h2>Mon nom à l'envers s'écrit <?php echo inverseName($name) ?>. Ah. Ah. Ah.</h2>
        <h2><?php coffeeOrDestruction() ?></h2>
        <h2><?php findNumber($MysteriousNumner) ?></h2>
        <h2><?php findNumberDicotomie($MysteriousNumner) ?></h2>
</main>
