<?php
$students = [
    [
        "firstName" => "James",
        "lastName" => "Fields",
        "grades" => [12, 11, 15],
        "average" => -1
    ],
    [
        "firstName" => "Richard",
        "lastName" => "Stein",
        "grades" => [18, 12, 13],
        "average" => -1
    ],
    [
        "firstName" => "Mark",
        "lastName" => "Hartoff",
        "grades" => [9, 11, 10],
        "average" => -1
    ],
    [
        "firstName" => "Thomas",
        "lastName" => "Nestle",
        "grades" => [9, 8, 5],
        "average" => -1
    ],
    [
        "firstName" => "Jeremy",
        "lastName" => "Brent",
        "grades" => [18, 15, 16],
        "average" => -1
    ]
];
?>

<?php
    function average(array $gradeTab) : float{
        $result = 0;
        foreach ($gradeTab as $grade){
            $result = $result + $grade;
        }
        return $result = $result/count($gradeTab);
    }
    
    function color(float $average) : string{
        if($average < 10){
            return "red";
        }
        elseif($average < 13){
            return "orange";
        }
        else{
            return "green";
        }
    }
?>



<!doctype html>
<html lang="fr">
<head>
    <!--Encodage des caractères-->
    <meta charset="utf-8">
    <!--Titre affiché dans l'onglet-->
    <title>Titre de la page</title>

    <!--Lien vers la feuille de style-->
    <link rel="stylesheet" href="style.css">
</head>

<?php foreach ($students as $student){ ?>
<article class="<?php echo color(average($student["grades"])) ?>">
    <header>
        <h1><?php echo "{$student["firstName"]} {$student["lastName"]}"; ?></h1>
    </header>
    <section>
        <h2>Notes : </h2>
        <ul>
            <?php foreach ($student["grades"] as $student["grade"]){ ?>
            <li><?php echo "{$student["grade"]}" ?></li>
            <?php } ?>
        </ul>
    </section>
    <footer>
        <h3><?php echo round(average($student["grades"]), 2) ?></h3>
    </footer>
</article>
<?php } ?>

